### ISSUE TITLE
Declare support for node 14?

### ISSUE THREAD

**Issue by makepanic** [ClarkSource/eslint-config#419]
Hi,

Thanks for maintaining this useful package.
I noticed that the packages declare node engine support with `^10.0 || ^12.0 || ^13.0`.
Node 13 was no LTS version and is currently outside its maintenance time frame. ( https://nodejs.org/en/about/releases/ )

Would it be ok if I create a PR to also add 14 to the engine list? Node 14 will enter active LTS phase in 2020-10-20.

![node lts](https://raw.githubusercontent.com/nodejs/Release/master/schedule.svg?sanitize=true)

**Comment by buschtoens** [comment]
Absolutely! I'd love that.

If you don't have the time for it, that's also fine. I need to update and re-release this package in the next days any way. :)
